# Setup
title:               Lordva
tagline:             'What the hell is this'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://lordva.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Louis Chabanon
  url:               https://twitter.com/laerolithe
  email:             lordva.pro@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-169300940-2
